/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useControls } from 'leva'


export function Fox(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./Fox/glTF-Binary/Fox.glb')  
  const { actions } = useAnimations(animations, group) 
  
  const {animationName} = useControls({
    animationName: {options: ['Survey', 'Run', 'Walk']}
  })

  useEffect(() => {            
    const action = actions[animationName]    
    action.reset().fadeIn(0.5).play()   
    
    // Clean up phase
    return () => {
        action.fadeOut(0.5)
    }

  }, [animationName])
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="root">
          <skinnedMesh
            name="fox"
            geometry={nodes.fox.geometry}
            material={materials.fox_material}
            skeleton={nodes.fox.skeleton}
          />
          <primitive object={nodes._rootJoint} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Fox.glb')
